### ISSUE TITLE
Texto ultrapassando a div

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#11]
@diogenesjup sei que voce está mexendo nisso, mas o texto do nome do professor está ultrapassando a div, conforme imagem abaixo:

<img width="420" alt="image" src="https://github.com/diogenesjup/Flat-Out-School/assets/26767987/bb1ddf22-bcab-4987-8b08-b39f77acc4f5">

<img width="367" alt="image" src="https://github.com/diogenesjup/Flat-Out-School/assets/26767987/9534b63d-afb3-4125-ae4d-11dd42700fed">

**Comment by diogenesjup** [comment]
Eu fechei essa inssue, por que ela foi enviada antes da liberação do material. Ver vídeo do item 5.1 para detalhes
