### ISSUE TITLE
Sessões não estão abrindo automáticamente

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#14]
@diogenesjup tudo bem?

Não estou conseguindo acessar rapidamente as sessões da area do professor, clico várias vezes e demora para abrir:

<img width="837" alt="image" src="https://github.com/diogenesjup/Flat-Out-School/assets/26767987/3876ca84-a522-44fc-8a13-2497cf14f373">

**Comment by diogenesjup** [comment]
O "Click" está no texto da frase, e ai ao clicar em áreas fora do texto, como na área cinza, acabava provocando esse problema na experiência de navegação.

Fiz uma correção, e agora toda a área cinza é clicável (online no MVP1)
