### ISSUE TITLE
[Dúvida] Link do Huddle

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#3]
@diogenesjup consegue me ajudar com isso?

Quando tento acessar o huddle dá esse erro?

<img width="1388" alt="image" src="https://github.com/diogenesjup/Flat-Out-School/assets/26767987/a48521a0-7ed0-4953-94e2-297f0290260c">

**Comment by diogenesjup** [comment]
Corrigido
