### ISSUE TITLE
[Dúvida] Cadastro de usuário

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#4]
@diogenesjup Fiz o cadastro do usuário nessa url: https://homologacao.flatoutschool.com/mvp1/cadastro/

Porém apresenta o erro abaixo, outro ponto não estou conseguindo setar a label ai do lado para colocar como dúvida, será que precisa habilitar esse campo?

<img width="667" alt="image" src="https://github.com/diogenesjup/Flat-Out-School/assets/26767987/1b02db4d-953c-4781-8d66-d07b09706ac7">

![image](https://github.com/diogenesjup/Flat-Out-School/assets/26767987/224b42e7-8cc0-495c-a58c-b9ec210f5984)

**Comment by diogenesjup** [comment]
Corrigido
