### ISSUE TITLE
Colocar texto quando o aluno comprar um produto e/ou se cadastrar

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#6]
@diogenesjup segue o texto para colocar na mensagem do bot, quando o aluno comprar um produto:

🚀 Parabéns pela aquisição do seu novo produto da Flat Out School! Sua jornada em direção a um novo idioma começa agora. 🚀

**Comment by diogenesjup** [comment]
E o texto de novo cadastro? @TomAlves1  Será mantido o 

"Olá ".$primeiro_nome
"tudo bem? 😊"
"Eu sou o Cleiton Alves aqui da Flat Out School, Seu cadastro foi realizado com sucesso! 🚀🇺🇸"
"Agora você vai aprender um novo idioma com a gente 😊"

?

**Comment by TomAlves1** [comment]
Pode manter esse texto, conseguimos pegar o nome do usuário corrente? por exemplo, se tivermos mais de um atendente?

**Comment by diogenesjup** [comment]
Mas como vamos saber quem é o usuário/atendente? (no caso do WhatsApp)

**Comment by TomAlves1** [comment]
Exatamente, esse é o ponto, ou podemos deixar um nome genérico msm né? ou deixarmos um texto generico, vou verificar aqui e te retorno

**Comment by TomAlves1** [comment]
@diogenesjup deixei mais genérico o texto assim: 

Olá, aqui é da equipe de atendimento Flat Out School. Seu cadastro foi concluído com sucesso! Agora você vai aprender um novo idioma conosco! Você tem alguma dúvida referente ao seu cadastro? 😊 🚀🇺🇸🇪🇸🇫🇷🇩🇪

Pode usar esse msm!

**Comment by diogenesjup** [comment]
![image](https://github.com/diogenesjup/Flat-Out-School/assets/3137920/9e33f0b0-672c-4a96-bec1-d501a423dddf)
Feito
