### ISSUE TITLE
Cancelamento de aula

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#7]
@diogenesjup no nosso contrato diz o  seguinte:

 Reserva-se também a CONTRATADA a possibilidade de cancelamento da aula, em virtude da disponibilidade do professor escolhido pelo aluno, falta do aluno justificada e instabilidade da plataforma. Nessa hipótese, poderá ocorrer a reposição da aula dentro do prazo de 30(trinta) dias.

Você pensou em como podemos repor essas aulas para o aluno nesse caso?

**Comment by diogenesjup** [comment]
Na verdade nesses casos, a aula não será considerada como dada/gasta, logo, ele ainda poderá reagenda-la.
