### ISSUE TITLE
Painel do professor

### ISSUE THREAD

**Issue by TomAlves1** [diogenesjup/Flat-Out-School#9]
@diogenesjup acessei o painel do professor pelo usuário do professor mas aparece vários links, consegue verificar depois?

<img width="1413" alt="image" src="https://github.com/diogenesjup/Flat-Out-School/assets/26767987/1de1a424-ee98-4242-aab9-65089703c5bd">

**Comment by diogenesjup** [comment]
Esse ainda é o painel antigo, o painel oficial do professor é outro
